name: GitLab Custom CICD
description: 'Runs a gitlab runner'
author: 'Metril'
branding:
  icon: 'server'
  color: 'purple'
inputs:
  registration-token:
    description: 'Private token'
    required: true
  project-id:
    description: 'Project ID'
    required: true
  gitlab-url:
    description: 'GitLab URL'
    required: true
  name:
    description: 'Runner name'
    required: true
  tag-list:
    description: 'Tag list to bind with the runner'
    required: true
  docker-image:
    description: 'Docker image used by runner'
    required: false
    default: 'docker:19.03.12'
  run-untagged:
    description: "Parameter that allows or not to pick untagged jobs"
    required: false
    default: 'true'
  access-level:
    description: 'Parameter to create or not a protected runner'
    required: false
    default: "not_protected"
runs:
  using: 'node12'
  main: 'dist/index.js'
