name: GitLab Custom CICD
description: 'Runs a gitlab runner'
author: 'Metril'
branding:
  icon: 'server'
  color: 'purple'
inputs:
  authentication-token:
    description: 'Authentication token'
    required: true
  gitlab-url:
    description: 'GitLab URL'
    required: true
  name:
    description: 'Runner name'
    required: true
  docker-image:
    description: 'Docker image used by runner'
    required: false
    default: 'docker:19.03.12'
  delete-runner:
    description: 'Delete runner configuration'
    required: false
    default: "false"
runs:
  using: 'node12'
  main: 'dist/index.js'
